# Generated by Django 5.1.1 on 2024-09-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_customuser_cedula_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
