# Generated by Django 5.1.1 on 2024-09-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_usercaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
