# Generated by Django 5.1.1 on 2024-10-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0007_customtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.TextField()),
                ("author", models.CharField(max_length=255)),
            ],
        ),
    ]
