# Generated by Django 5.0.9 on 2024-11-21 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0010_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="customuser",
            name="room_address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
