# Generated by Django 5.0.9 on 2025-02-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0013_alter_innerprestamo_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial", models.CharField(max_length=255, unique=True)),
                ("directory", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
