# Generated by Django 5.0.9 on 2025-02-24 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0014_fileupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="innerprestamo",
            name="cuota_especial",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("no_or_yes", "No or Yes")],
                default="no",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="innerprestamo",
            name="garantia",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("no_or_yes", "No or Yes")],
                default="no",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="innerprestamo",
            name="mmc",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="innerprestamo",
            name="modalidad",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("no_or_yes", "No or Yes")],
                default="no",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="innerprestamo",
            name="montomax",
            field=models.DecimalField(
                decimal_places=2,
                default=800,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="innerprestamo",
            name="montomin",
            field=models.DecimalField(
                decimal_places=2,
                default=800,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="innerprestamo",
            name="numcuotamins",
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="innerprestamo",
            name="numcuotasmax",
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="innerprestamo",
            name="tasa",
            field=models.DecimalField(
                decimal_places=2,
                default=12,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
    ]
